// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vffcmdvidlzicubywpsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmZmNtZHZpZGx6aWN1Ynl3cHNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTcwNTAsImV4cCI6MjA3MTMzMzA1MH0.Ps48KzTD53Cme_3-yKJrZmICzLj_L9wp2EIQxuzDmp8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});